MCAL/EEPROM/EEPROM.o MCAL/EEPROM/EEPROM.o: ../MCAL/EEPROM/EEPROM.c \
  ../MCAL/EEPROM/../../LIB/STD_TYPES.h \
  ../MCAL/EEPROM/../../LIB/BIT_MATH.h

../MCAL/EEPROM/../../LIB/STD_TYPES.h:

../MCAL/EEPROM/../../LIB/BIT_MATH.h:
